# Generated by Django 2.2.14 on 2020-07-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Pan_Number', models.CharField(max_length=20)),
                ('Age', models.IntegerField(max_length=3)),
                ('Gender', models.CharField(max_length=20)),
                ('Email_Add', models.CharField(max_length=100)),
            ],
        ),
    ]
