# Generated by Django 2.2.14 on 2020-07-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hannovit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
